title: Fourier-GRX-N1 SDK
description: 开发文档
remote_theme: just-the-docs/just-the-docs

# 插件配置
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-seo-tag

# Logo 配置
logo: "/assets/images/fourier_logo.png"
logo_alt: "Fourier Intelligence"

# 搜索和导航配置
search_enabled: true
collapse_navigation: true
navigation_fixed: true
navigation_sticky: true
navigation_fold: true

# 默认布局配置
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# 外部链接配置
aux_links:
  "GitHub 仓库":
    - "//github.com/FFTAI/Wiki-GRx-Pipeline/tree/FourierN1"
aux_links_new_tab: true

# Markdown 配置
markdown: kramdown
kramdown:
  auto_ids: true
  toc_levels: 1..3
  syntax_highlighter: rouge

# 其他配置
heading_anchors: true
back_to_top: true
back_to_top_text: "返回顶部"
footer_content: "Copyright &copy; Fourier Intelligence"
